Repository Swebi/Nexus, pull requests merged in 2024-07, with the labels that each got.

#5 Bootstrap Server
  server/.gitignore
  server/biome.json
  server/package.json
  server/pnpm-lock.yaml
  server/src/api/index.ts
  server/src/api/test/test.controller.ts
  server/src/config/index.ts
  server/src/index.ts
  server/src/loaders/database.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/loaders/logger.ts
  server/src/middlewares/errorHandler.ts
  server/src/shared/errors.ts
  server/tsconfig.json
Labels: backend

#7 feat: add navbar and hero
  client/index.html
  client/package.json
  client/pnpm-lock.yaml
  client/src/App.jsx
  client/src/assets/react-flow.png
  client/src/components/Hero.jsx
  client/src/components/Navbar.jsx
  client/src/index.css
  client/tailwind.config.js
Labels: UI

#9 Add react flow hero
  client/src/App.jsx
  client/src/components/Flow.jsx
  client/src/components/Hero.jsx
  client/src/index.css
Labels: UI

#14 Add Router, Dashboard, Layout
  client/package.json
  client/pnpm-lock.yaml
  client/src/App.jsx
  client/src/components/Flow.jsx
  client/src/components/Hero.jsx
  client/src/components/Navbar.jsx
  client/src/data/nodes-edges.js
  client/src/index.css
  client/src/main.jsx
  client/src/pages/Dashboard.jsx
Labels: frontend

#12 Get Folder Details
  server/package.json
  server/pnpm-lock.yaml
  server/src/api/folder/folder.controller.ts
  server/src/api/folder/folder.schema.ts
  server/src/api/folder/folder.service.ts
  server/src/api/index.ts
Labels: enhancement, backend

#17 Fix IgnoreFiles
  server/src/api/folder/folder.controller.ts
  server/src/api/folder/folder.service.ts
Labels: bug

#19 Add input states for request body
  client/src/pages/Dashboard.jsx
  client/src/utils/generateGraphData.js
Labels: frontend

#24 Add Generate & Save function
  client/package.json
  client/src/data/nodes-edges.js
  client/src/pages/Dashboard.jsx
  client/src/utils/generateGraphData.js
  client/src/utils/getLayoutedElements.js
  client/src/utils/saveLayout.js
  pnpm-lock.yaml
Labels: frontend

#26 Add Startup Panel
  client/src/data/nodes-edges.js
  client/src/pages/Dashboard.jsx
Labels: frontend

#28 Add layout upload json
  client/src/pages/Dashboard.jsx
Labels: frontend

#31 Add github templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST.md
Labels: enhancement

#32 Add styling for nodes
  client/src/utils/generateGraphData.js
  client/src/utils/getColor.js
Labels: frontend

#34 Create Readme
  README.md
Labels: enhancement

#36 feat: add file details
  client/src/pages/Dashboard.jsx
  client/src/utils/generateGraphData.js
Labels: frontend
